"""initial schema

Revision ID: 275326344062
Revises: 
Create Date: 2026-09-01 11:48:29.109140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import analyzer.db.types


# revision identifiers, used by Alembic.
revision: str = '275326344062'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('target_country', sa.String(length=2), nullable=False),
    sa.Column('target_language', sa.String(length=10), nullable=False),
    sa.Column('business_type', sa.String(length=255), nullable=False),
    sa.Column('website_type', sa.Enum('SERVICES', 'ECOMMERCE', 'SAAS', 'OTHER', name='websitetype', native_enum=False), nullable=False),
    sa.Column('priority_services', analyzer.db.types.PortableJSONB(), nullable=True),
    sa.Column('api_budget_usd', sa.Float(), nullable=False),
    sa.Column('api_spend_usd', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clusters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('intent', sa.Enum('COMMERCIAL', 'TRANSACTIONAL', 'INFORMATIONAL', 'NAVIGATIONAL', name='keywordintent', native_enum=False), nullable=True),
    sa.Column('total_search_volume', sa.Integer(), nullable=True),
    sa.Column('clustering_method', sa.String(length=50), nullable=False),
    sa.Column('clustering_version', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('domains',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('hostname', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('CLIENT', 'COMPETITOR', name='domainrole', native_enum=False), nullable=False),
    sa.Column('competitor_source', sa.Enum('USER_PROVIDED', 'DISCOVERED', name='competitorsource', native_enum=False), nullable=True),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.Column('added_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'hostname', name='uq_domain_project_hostname')
    )
    op.create_table('keywords',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('text_normalized', sa.String(length=500), nullable=False),
    sa.Column('locale', sa.String(length=10), nullable=False),
    sa.Column('search_volume', sa.Integer(), nullable=True),
    sa.Column('cpc', sa.Float(), nullable=True),
    sa.Column('competition', sa.Float(), nullable=True),
    sa.Column('intent', sa.Enum('COMMERCIAL', 'TRANSACTIONAL', 'INFORMATIONAL', 'NAVIGATIONAL', name='keywordintent', native_enum=False), nullable=True),
    sa.Column('intent_method', sa.Enum('PROVIDER', 'HEURISTIC', 'LLM', name='intentmethod', native_enum=False), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'text_normalized', 'locale', name='uq_keyword_project_text_locale')
    )
    op.create_table('llm_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('stage', sa.Enum('INTERPRETATION', 'TALKING_POINTS', 'PAGE_STRUCTURE', 'EEAT', name='llmrunstage', native_enum=False), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('input_payload', analyzer.db.types.PortableJSONB(), nullable=False),
    sa.Column('output_payload', analyzer.db.types.PortableJSONB(), nullable=False),
    sa.Column('validation_status', sa.Enum('PASSED', 'REGENERATED', 'FALLBACK', name='validationstatus', native_enum=False), nullable=False),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('cost_estimate', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('opportunities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('TRAFFIC_GAP', 'SEMANTIC_GAP', 'COMMERCIAL_PAGE_GAP', 'PAGE_STRUCTURE_GAP', 'CONTENT_GAP', 'BACKLINK_GAP', 'EEAT_GAP', 'TECHNICAL_GAP', 'QUICK_WINS', name='opportunitytype', native_enum=False), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('evidence', analyzer.db.types.PortableJSONB(), nullable=True),
    sa.Column('impact', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Integer(), nullable=True),
    sa.Column('effort', sa.Integer(), nullable=True),
    sa.Column('business_relevance', sa.Integer(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('scoring_version', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cluster_keywords',
    sa.Column('cluster_id', sa.Integer(), nullable=False),
    sa.Column('keyword_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['clusters.id'], ),
    sa.ForeignKeyConstraint(['keyword_id'], ['keywords.id'], ),
    sa.PrimaryKeyConstraint('cluster_id', 'keyword_id')
    )
    op.create_table('cluster_url_map',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cluster_id', sa.Integer(), nullable=False),
    sa.Column('domain_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('best_position', sa.Integer(), nullable=True),
    sa.Column('opportunity_status', sa.Enum('COVERED', 'WEAK', 'MISSING', name='opportunitystatus', native_enum=False), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['clusters.id'], ),
    sa.ForeignKeyConstraint(['domain_id'], ['domains.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('crawls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', name='crawlstatus', native_enum=False), nullable=False),
    sa.Column('page_budget', sa.Integer(), nullable=False),
    sa.Column('pages_crawled', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['domain_id'], ['domains.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('generated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('pipeline_version', sa.String(length=20), nullable=False),
    sa.Column('sections', analyzer.db.types.PortableJSONB(), nullable=False),
    sa.Column('file_ref', sa.Text(), nullable=True),
    sa.Column('llm_run_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['llm_run_id'], ['llm_runs.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('seo_metrics_raw',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('endpoint', sa.String(length=255), nullable=False),
    sa.Column('request_params', analyzer.db.types.PortableJSONB(), nullable=False),
    sa.Column('raw_response', analyzer.db.types.PortableJSONB(), nullable=False),
    sa.Column('estimated_cost_usd', sa.Float(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['domain_id'], ['domains.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('domain_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('organic_traffic', sa.Integer(), nullable=True),
    sa.Column('organic_keywords', sa.Integer(), nullable=True),
    sa.Column('top3', sa.Integer(), nullable=True),
    sa.Column('top10', sa.Integer(), nullable=True),
    sa.Column('top20', sa.Integer(), nullable=True),
    sa.Column('top100', sa.Integer(), nullable=True),
    sa.Column('traffic_value', sa.Float(), nullable=True),
    sa.Column('branded_keywords', sa.Integer(), nullable=True),
    sa.Column('nonbranded_keywords', sa.Integer(), nullable=True),
    sa.Column('source_raw_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['domain_id'], ['domains.id'], ),
    sa.ForeignKeyConstraint(['source_raw_id'], ['seo_metrics_raw.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('keyword_positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('keyword_id', sa.Integer(), nullable=False),
    sa.Column('domain_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('source_raw_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['domain_id'], ['domains.id'], ),
    sa.ForeignKeyConstraint(['keyword_id'], ['keywords.id'], ),
    sa.ForeignKeyConstraint(['source_raw_id'], ['seo_metrics_raw.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('crawl_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('indexable', sa.Boolean(), nullable=True),
    sa.Column('robots_directives', analyzer.db.types.PortableJSONB(), nullable=True),
    sa.Column('canonical', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('meta_description', sa.Text(), nullable=True),
    sa.Column('h1', sa.Text(), nullable=True),
    sa.Column('h2', analyzer.db.types.PortableJSONB(), nullable=True),
    sa.Column('h3', analyzer.db.types.PortableJSONB(), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=True),
    sa.Column('page_type', sa.String(length=50), nullable=True),
    sa.Column('page_type_confidence', sa.Float(), nullable=True),
    sa.Column('page_type_method', sa.Enum('RULE', 'LLM', name='pagetypemethod', native_enum=False), nullable=True),
    sa.Column('page_depth', sa.Integer(), nullable=True),
    sa.Column('structured_data', analyzer.db.types.PortableJSONB(), nullable=True),
    sa.Column('breadcrumbs', analyzer.db.types.PortableJSONB(), nullable=True),
    sa.Column('pagination', analyzer.db.types.PortableJSONB(), nullable=True),
    sa.Column('hreflang', analyzer.db.types.PortableJSONB(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('raw_html_ref', sa.Text(), nullable=True),
    sa.Column('rendered_with_js', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['crawl_id'], ['crawls.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sales_talking_points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('primary_angle', sa.Text(), nullable=False),
    sa.Column('supporting_arguments', analyzer.db.types.PortableJSONB(), nullable=False),
    sa.Column('quick_win_summary', sa.Text(), nullable=True),
    sa.Column('what_to_sell', analyzer.db.types.PortableJSONB(), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('technical_findings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('crawl_id', sa.Integer(), nullable=False),
    sa.Column('issue_type', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.Enum('CRITICAL', 'NOTABLE', 'MINOR', name='findingseverity', native_enum=False), nullable=False),
    sa.Column('affected_url_count', sa.Integer(), nullable=False),
    sa.Column('affected_urls_sample', analyzer.db.types.PortableJSONB(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('materiality_pct', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['crawl_id'], ['crawls.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('page_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('page_id', sa.Integer(), nullable=False),
    sa.Column('src', sa.Text(), nullable=False),
    sa.Column('alt_text', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('page_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('page_id', sa.Integer(), nullable=False),
    sa.Column('target_url', sa.Text(), nullable=False),
    sa.Column('link_type', sa.Enum('INTERNAL', 'EXTERNAL', name='linktype', native_enum=False), nullable=False),
    sa.Column('anchor_text', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('page_links')
    op.drop_table('page_images')
    op.drop_table('technical_findings')
    op.drop_table('sales_talking_points')
    op.drop_table('pages')
    op.drop_table('keyword_positions')
    op.drop_table('domain_metrics')
    op.drop_table('seo_metrics_raw')
    op.drop_table('reports')
    op.drop_table('crawls')
    op.drop_table('cluster_url_map')
    op.drop_table('cluster_keywords')
    op.drop_table('opportunities')
    op.drop_table('llm_runs')
    op.drop_table('keywords')
    op.drop_table('domains')
    op.drop_table('clusters')
    op.drop_table('projects')
    # ### end Alembic commands ###
